[package]
name = "bevy_pxo"
version = "0.2.0"
edition = "2021"
license = "MIT or Apache-2.0"

[dependencies]
bevy = { version = "^0.13", default-features = false, features = ["bevy_asset", "bevy_render"] }
image = "0.24.7"
pxo = "0.2.0"
