[package]
name = "bevy_pxo"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = { version = "0.12.0", default-features = false, features = ["bevy_asset", "bevy_render"] }
pxo = "0.1.0"
